services:
  db:
    image: postgres:14-alpine
    container_name: brasileirao_pipeline_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  brasileirao_pipeline:
    build: .
    container_name: brasileirao_pipeline
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - POSTGRES_HOST: db

volumes:
  postgres_data:
